### ISSUE TITLE
zip archive cannot be read using SharpZipLib in C#

### ISSUE THREAD

**Issue by silverhammermba** [ZipArchive/ZipArchive#626]
Updating from 2.2.3 to 2.4.2, I get this exception when using SharpZipLib to extract

    [ICSharpCode.SharpZipLib.Zip.ZipException: Size invalid for descriptor
      at ICSharpCode.SharpZipLib.Zip.ZipFile.TestLocalHeader(ZipEntry entry, HeaderTest tests)
      at ICSharpCode.SharpZipLib.Zip.ZipFile.LocateEntry(ZipEntry entry)
      at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(Int64 entryIndex)
      at ICSharpCode.SharpZipLib.Zip.ZipFile.GetInputStream(ZipEntry entry)

I get a slightly different error when using 2.3.0: `[ICSharpCode.SharpZipLib.Zip.ZipException: Extra data extended Zip64 information length is invalid`

**Comment by Coeur** [comment]
I changed zip64 logic to be "AUTO": it will only use zip64 when the size needs it.
